apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always
          name: homeassistant
          env:
            - name: TZ
              value: "Australia/Brisbane"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_RAW
                - NET_ADMIN
                - SYS_NICE
                - CHOWN
          ports:
            - containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: '/config'
            - name: localtime
              mountPath: '/etc/localtime'
              readOnly: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /opt/volumes/homeassistant/config
        - name: localtime
          hostPath:
            path: /etc/localtime
