on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-deployment
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/dalethestirling/4afce63eb152c8763bb7b40260bcac39
          gist_title: deployment.yaml
          gist_description: Kubernetes files for Home assistant on Kubernetes
          github_file: deployment.yaml
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-service
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/dalethestirling/4afce63eb152c8763bb7b40260bcac39
          gist_title: service.yaml
          gist_description: Kubernetes files for Home assistant on Kubernetes
          github_file: service.yaml
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-namespace
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/dalethestirling/4afce63eb152c8763bb7b40260bcac39
          gist_title: namespace.yaml
          gist_description: Kubernetes files for Home assistant on Kubernetes
          github_file: namespace.yaml
